import type { InterfaceLocale } from '@/lib/locale';

const ru = {
  account:'Ваш аккаунт', guestMode:'Гостевой режим', guestDescription:'Сейчас прогресс хранится в этом браузере. Войдите, чтобы продолжить обучение на телефоне и сохранить личный профиль.', guestLogin:'Войти · Google или email',
  profile:'Личный профиль', name:'Ваше имя', saveName:'Сохранить имя', wait:'Подождите…', addPhoto:'Добавить фото', removePhoto:'Удалить фото', photoHint:'JPEG, PNG или WebP до 5 МБ. Фото обрезается до квадрата и хранится приватно.',
  profileSaved:'Профиль сохранён.', profileError:'Не удалось сохранить профиль.', profileRetry:'Не удалось сохранить профиль. Попробуйте ещё раз.', nameError:'Не удалось сохранить имя.', nameInvalid:'Имя должно содержать от 2 до 60 символов.', photoInvalid:'Недопустимое фото.', loginUnavailable:'Вход не подключён.', photoUploaded:'Фото обновлено.', photoUploadError:'Не удалось загрузить фото.', photoUploadRetry:'Не удалось загрузить фото. Попробуйте ещё раз.', photoRemoved:'Фото удалено.', photoRemoveError:'Не удалось удалить фото.', photoFormat:'JPEG, PNG или WebP, до 5 МБ.', photoSize:'Изображение слишком большое.', photoProcess:'Не удалось обработать фото.',
  devices:'Сохранение и устройства', deviceDescription:'Ваши ответы, XP, заметки, настройки и код доступны только вашему аккаунту. На другом устройстве войдите в тот же аккаунт.', sync:'Синхронизировать', importGuest:'Добавить прогресс гостя из этого браузера', noGuestProgress:'Гостевого прогресса пока нет.', guestImported:'Гостевой прогресс добавлен. Статус облака показан ниже.', guestImportError:'Не удалось прочитать гостевой прогресс. Исходные данные сохранены.',
  local:'В этом браузере', syncing:'Сохраняем в облако…', synced:'Сохранено в облаке', offline:'Нет сети · изменения сохранены в браузере', error:'Облако недоступно · изменения сохранены в браузере',
  phone:'Продолжить на телефоне', phoneDescription:'Сканируйте QR камерой, откройте сайт и войдите в тот же Google или email аккаунт. QR содержит только ссылку на сайт.', phoneAlt:'QR: открыть вход на телефоне', phoneError:'QR недоступен. Откройте этот сайт на телефоне.',
  security:'Защита аккаунта', checking:'Проверяем…', connected:'Authenticator подключён', ordinaryLogin:'Обычный вход', securityDescription:'Дополнительная защита через приложение на телефоне. Работает без SMS: Google Authenticator, Microsoft Authenticator, 2FAS и другие.', enrollScan:'1. Отсканируйте QR в приложении authenticator.', enrollCode:'2. Введите код, чтобы включить защиту.', enrollAlt:'QR для приложения authenticator', enrollManual:'Не получается сканировать? Введите ключ вручную', enrollHint:'Сохраните доступ к приложению: коды понадобятся при следующем входе. Этот QR и ключ никому не отправляйте.', appCode:'Код из приложения', enableSecurity:'Подключить защиту', cancel:'Отмена', requiredCode:'При входе потребуется код из приложения.', disable:'Отключить', enroll:'Подключить authenticator · QR', factorCheckError:'Не удалось проверить authenticator.', enrollError:'Не удалось подключить authenticator. Попробуйте позже.', verifyError:'Код не принят. Возьмите новый код из приложения.', cancelError:'Не удалось отменить подключение. Повторите попытку.', factorRemoved:'Authenticator отключён.', factorRemoveError:'Не удалось отключить authenticator. Подтвердите вход и повторите.',
  session:'Сессия', sessionDescription:'Вход сохраняется на этом устройстве после закрытия браузера. Выход закроет аккаунт здесь; на других устройствах он останется открытым.', logout:'Выйти', logoutAccount:'Выйти из аккаунта',
  challengeTitle:'Подтвердите вход', challengeDescription:'Введите 6 цифр из Google Authenticator, Microsoft Authenticator или другого приложения.', challengeCode:'Код authenticator', confirm:'Подтвердить', challengeError:'Не удалось подтвердить код. Возьмите новый код из приложения.',
  newPassword:'Новый пароль', recoveryDescription:'После сохранения войдите с новым паролем.', repeatPassword:'Повторите пароль', savePassword:'Сохранить пароль', passwordMismatch:'Пароли не совпадают.', recoveryError:'Не удалось сменить пароль. Повторите запрос восстановления.',
  opening:'Открываем ReactMentor…', restoring:'Восстанавливаем ваш вход', openFailed:'Не удалось открыть аккаунт', openError:'Не удалось открыть аккаунт.', retry:'Повторить', assuranceError:'Не удалось проверить защиту аккаунта.', profileLoadError:'Не удалось загрузить профиль. Проверьте подключение и настройку базы.', connectionError:'Не удалось проверить подключение. Сохранённый вход восстановится, когда появится интернет.', restoreError:'Сохранённый вход временно недоступен. Подключитесь к интернету — аккаунт восстановится автоматически.', sessionExpired:'Сессия истекла. Войдите ещё раз.', sessionChanged:'Сессия изменилась. Повторите открытие аккаунта.', accountUnverified:'Не удалось подтвердить аккаунт. Войдите ещё раз.', loginIncomplete:'Вход не завершён. Повторите вход через Google или email.', logoutError:'Не удалось выйти. Повторите попытку.',
  emailUnconfirmed:'Подтвердите email по ссылке в письме, затем войдите.', invalidCredentials:'Не удалось войти. Проверьте email и пароль.', signupDisabled:'Регистрация сейчас закрыта. Попробуйте позже или войдите в существующий аккаунт.', weakPassword:'Пароль слишком простой. Используйте минимум 8 символов, буквы и цифры.', emailInvalid:'Проверьте адрес email: он не принят почтовым сервисом.', emailLimit:'Лимит отправки писем временно исчерпан. Попробуйте позже.', requestLimit:'Слишком много попыток. Подождите и попробуйте снова.', loginError:'Не удалось войти. Проверьте email, пароль и подтверждение адреса.', requestError:'Не удалось отправить запрос. Проверьте данные и повторите позже.',
};

export type AccountCopyKey = keyof typeof ru;
type AccountCopy = Record<AccountCopyKey, string>;

export const ACCOUNT_COPY: Record<InterfaceLocale, AccountCopy> = {
  ru,
  en:{
    account:'Your account', guestMode:'Guest mode', guestDescription:'Progress is saved in this browser. Sign in to continue on your phone and keep a personal profile.', guestLogin:'Sign in · Google or email',
    profile:'Personal profile', name:'Your name', saveName:'Save name', wait:'Please wait…', addPhoto:'Add photo', removePhoto:'Remove photo', photoHint:'JPEG, PNG or WebP up to 5 MB. Photos are cropped to a square and stored privately.',
    profileSaved:'Profile saved.', profileError:'Could not save your profile.', profileRetry:'Could not save your profile. Please try again.', nameError:'Could not save your name.', nameInvalid:'Your name must contain 2 to 60 characters.', photoInvalid:'Invalid photo.', loginUnavailable:'Sign-in is not configured.', photoUploaded:'Photo updated.', photoUploadError:'Could not upload the photo.', photoUploadRetry:'Could not upload the photo. Please try again.', photoRemoved:'Photo removed.', photoRemoveError:'Could not remove the photo.', photoFormat:'JPEG, PNG or WebP, up to 5 MB.', photoSize:'The image is too large.', photoProcess:'Could not process the photo.',
    devices:'Saving and devices', deviceDescription:'Your answers, XP, notes, settings and code are available only to your account. Sign in to the same account on another device.', sync:'Sync now', importGuest:'Import guest progress from this browser', noGuestProgress:'There is no guest progress yet.', guestImported:'Guest progress added. Cloud status is shown below.', guestImportError:'Could not read guest progress. The original data is preserved.',
    local:'In this browser', syncing:'Saving to the cloud…', synced:'Saved to the cloud', offline:'Offline · changes saved in this browser', error:'Cloud unavailable · changes saved in this browser',
    phone:'Continue on your phone', phoneDescription:'Scan the QR with your camera, open the site and sign in to the same Google or email account. The QR contains only a link to the site.', phoneAlt:'QR: open sign-in on your phone', phoneError:'QR unavailable. Open this site on your phone.',
    security:'Account security', checking:'Checking…', connected:'Authenticator connected', ordinaryLogin:'Standard sign-in', securityDescription:'Extra protection with an app on your phone. No SMS needed: Google Authenticator, Microsoft Authenticator, 2FAS and others.', enrollScan:'1. Scan the QR in your authenticator app.', enrollCode:'2. Enter a code to enable protection.', enrollAlt:'QR for the authenticator app', enrollManual:'Cannot scan? Enter the key manually', enrollHint:'Keep access to the app: you will need its codes when you next sign in. Do not share this QR or key with anyone.', appCode:'Code from the app', enableSecurity:'Enable protection', cancel:'Cancel', requiredCode:'Sign-in will require a code from the app.', disable:'Disconnect', enroll:'Connect authenticator · QR', factorCheckError:'Could not check the authenticator.', enrollError:'Could not connect the authenticator. Try again later.', verifyError:'Code not accepted. Get a new code from the app.', cancelError:'Could not cancel setup. Please try again.', factorRemoved:'Authenticator disconnected.', factorRemoveError:'Could not disconnect the authenticator. Verify your sign-in and try again.',
    session:'Session', sessionDescription:'You stay signed in on this device after closing the browser. Signing out closes your account here; other devices stay signed in.', logout:'Log out', logoutAccount:'Log out of your account',
    challengeTitle:'Verify your sign-in', challengeDescription:'Enter 6 digits from Google Authenticator, Microsoft Authenticator or another app.', challengeCode:'Authenticator code', confirm:'Verify', challengeError:'Could not verify the code. Get a new code from the app.',
    newPassword:'New password', recoveryDescription:'After saving, sign in with your new password.', repeatPassword:'Repeat password', savePassword:'Save password', passwordMismatch:'Passwords do not match.', recoveryError:'Could not change the password. Request password recovery again.',
    opening:'Opening ReactMentor…', restoring:'Restoring your sign-in', openFailed:'Could not open your account', openError:'Could not open your account.', retry:'Retry', assuranceError:'Could not check account security.', profileLoadError:'Could not load your profile. Check the connection and database setup.', connectionError:'Could not check the connection. Your saved sign-in will be restored when you are online.', restoreError:'Your saved sign-in is temporarily unavailable. Connect to the internet — your account will be restored automatically.', sessionExpired:'Your session has expired. Sign in again.', sessionChanged:'Your session changed. Try opening your account again.', accountUnverified:'Could not verify your account. Sign in again.', loginIncomplete:'Sign-in was not completed. Try Google or email again.', logoutError:'Could not sign out. Please try again.',
    emailUnconfirmed:'Confirm your email using the link in the message, then sign in.', invalidCredentials:'Could not sign in. Check your email and password.', signupDisabled:'Registration is currently closed. Try later or sign in to an existing account.', weakPassword:'Your password is too weak. Use at least 8 characters, letters and numbers.', emailInvalid:'Check your email address: the email service did not accept it.', emailLimit:'The email sending limit is temporarily reached. Try again later.', requestLimit:'Too many attempts. Wait and try again.', loginError:'Could not sign in. Check your email, password and email confirmation.', requestError:'Could not send the request. Check your details and try again later.',
  },
  tg:{
    account:'Аккаунти шумо', guestMode:'Ҳолати меҳмон', guestDescription:'Пешрафт ҳоло дар ҳамин браузер нигоҳ дошта мешавад. Барои идома дар телефон ва нигоҳ доштани профил ворид шавед.', guestLogin:'Воридшавӣ · Google ё email',
    profile:'Профили шахсӣ', name:'Номи шумо', saveName:'Нигоҳ доштани ном', wait:'Лутфан интизор шавед…', addPhoto:'Илова кардани акс', removePhoto:'Нест кардани акс', photoHint:'JPEG, PNG ё WebP то 5 МБ. Акс ба шакли мураббаъ бурида шуда, хусусӣ нигоҳ дошта мешавад.',
    profileSaved:'Профил нигоҳ дошта шуд.', profileError:'Профил нигоҳ дошта нашуд.', profileRetry:'Профил нигоҳ дошта нашуд. Бори дигар кӯшиш кунед.', nameError:'Ном нигоҳ дошта нашуд.', nameInvalid:'Ном бояд аз 2 то 60 аломат дошта бошад.', photoInvalid:'Акс нодуруст аст.', loginUnavailable:'Воридшавӣ пайваст нашудааст.', photoUploaded:'Акс нав шуд.', photoUploadError:'Акс бор нашуд.', photoUploadRetry:'Акс бор нашуд. Бори дигар кӯшиш кунед.', photoRemoved:'Акс нест шуд.', photoRemoveError:'Акс нест нашуд.', photoFormat:'JPEG, PNG ё WebP, то 5 МБ.', photoSize:'Тасвир хеле калон аст.', photoProcess:'Акс коркард нашуд.',
    devices:'Нигоҳдорӣ ва дастгоҳҳо', deviceDescription:'Ҷавобҳо, XP, ёддоштҳо, танзимот ва коди шумо танҳо ба аккаунти шумо дастрасанд. Дар дастгоҳи дигар ба ҳамин аккаунт ворид шавед.', sync:'Ҳамоҳанг кардан', importGuest:'Илова кардани пешрафти меҳмон аз ин браузер', noGuestProgress:'Ҳоло пешрафти меҳмон нест.', guestImported:'Пешрафти меҳмон илова шуд. Ҳолати абр дар поён нишон дода шудааст.', guestImportError:'Пешрафти меҳмон хонда нашуд. Маълумоти аслӣ нигоҳ дошта шудааст.',
    local:'Дар ҳамин браузер', syncing:'Дар абр нигоҳ дошта мешавад…', synced:'Дар абр нигоҳ дошта шуд', offline:'Шабака нест · тағйирот дар браузер нигоҳ дошта шуд', error:'Абр дастрас нест · тағйирот дар браузер нигоҳ дошта шуд',
    phone:'Идома дар телефон', phoneDescription:'QR-ро бо камера хонед, сайтро кушоед ва ба ҳамон аккаунти Google ё email ворид шавед. QR танҳо пайванди сайтро дорад.', phoneAlt:'QR: кушодани воридшавӣ дар телефон', phoneError:'QR дастрас нест. Ин сайтро дар телефон кушоед.',
    security:'Ҳифзи аккаунт', checking:'Санҷида мешавад…', connected:'Authenticator пайваст шуд', ordinaryLogin:'Воридшавии оддӣ', securityDescription:'Ҳифзи иловагӣ тавассути барнома дар телефон. Бе SMS кор мекунад: Google Authenticator, Microsoft Authenticator, 2FAS ва дигарҳо.', enrollScan:'1. QR-ро дар барномаи authenticator хонед.', enrollCode:'2. Барои фаъол кардани ҳифз кодро ворид кунед.', enrollAlt:'QR барои барномаи authenticator', enrollManual:'Хонда намешавад? Калидро дастӣ ворид кунед', enrollHint:'Дастрасӣ ба барномаро нигоҳ доред: ҳангоми воридшавии нав кодҳо лозим мешаванд. Ин QR ва калидро ба ҳеҷ кас нафиристед.', appCode:'Код аз барнома', enableSecurity:'Фаъол кардани ҳифз', cancel:'Бекор кардан', requiredCode:'Ҳангоми воридшавӣ код аз барнома лозим мешавад.', disable:'Қатъ кардан', enroll:'Пайваст кардани authenticator · QR', factorCheckError:'Authenticator санҷида нашуд.', enrollError:'Authenticator пайваст нашуд. Дертар кӯшиш кунед.', verifyError:'Код қабул нашуд. Аз барнома коди нав гиред.', cancelError:'Пайвастшавӣ бекор нашуд. Бори дигар кӯшиш кунед.', factorRemoved:'Authenticator қатъ шуд.', factorRemoveError:'Authenticator қатъ нашуд. Воридшавиро тасдиқ карда, такрор кунед.',
    session:'Сессия', sessionDescription:'Пас аз бастани браузер воридшавӣ дар ин дастгоҳ нигоҳ дошта мешавад. Баромадан аккаунтро дар ин ҷо мебандад; дар дастгоҳҳои дигар он кушода мемонад.', logout:'Баромадан', logoutAccount:'Баромадан аз аккаунт',
    challengeTitle:'Воридшавиро тасдиқ кунед', challengeDescription:'6 рақамро аз Google Authenticator, Microsoft Authenticator ё барномаи дигар ворид кунед.', challengeCode:'Коди authenticator', confirm:'Тасдиқ кардан', challengeError:'Код тасдиқ нашуд. Аз барнома коди нав гиред.',
    newPassword:'Рамзи нав', recoveryDescription:'Пас аз нигоҳдорӣ бо рамзи нав ворид шавед.', repeatPassword:'Рамзро такрор кунед', savePassword:'Нигоҳ доштани рамз', passwordMismatch:'Рамзҳо мувофиқ нестанд.', recoveryError:'Рамз иваз нашуд. Барқароркуниро бори дигар дархост кунед.',
    opening:'ReactMentor кушода мешавад…', restoring:'Воридшавии шумо барқарор мешавад', openFailed:'Аккаунт кушода нашуд', openError:'Аккаунт кушода нашуд.', retry:'Такрор кардан', assuranceError:'Ҳифзи аккаунт санҷида нашуд.', profileLoadError:'Профил бор нашуд. Пайвастшавӣ ва танзими пойгоҳи додаҳоро санҷед.', connectionError:'Пайвастшавӣ санҷида нашуд. Ҳангоми пайдо шудани интернет воридшавии сабтшуда барқарор мешавад.', restoreError:'Воридшавии сабтшуда муваққатан дастрас нест. Ба интернет пайваст шавед — аккаунт худкор барқарор мешавад.', sessionExpired:'Сессия ба охир расид. Бори дигар ворид шавед.', sessionChanged:'Сессия тағйир ёфт. Аккаунтро бори дигар кушоед.', accountUnverified:'Аккаунт тасдиқ нашуд. Бори дигар ворид шавед.', loginIncomplete:'Воридшавӣ анҷом наёфт. Бо Google ё email такрор кунед.', logoutError:'Баромадан имкон нашуд. Бори дигар кӯшиш кунед.',
    emailUnconfirmed:'Email-ро бо пайванди нома тасдиқ карда, баъд ворид шавед.', invalidCredentials:'Воридшавӣ имкон нашуд. Email ва рамзро санҷед.', signupDisabled:'Бақайдгирӣ ҳоло баста аст. Дертар кӯшиш кунед ё ба аккаунти мавҷуда ворид шавед.', weakPassword:'Рамз хеле сода аст. Камаш 8 аломат, ҳарф ва рақам истифода баред.', emailInvalid:'Суроғаи email-ро санҷед: хидмати почта онро қабул накард.', emailLimit:'Маҳдудияти фиристодани номаҳо муваққатан расид. Дертар кӯшиш кунед.', requestLimit:'Кӯшишҳо хеле зиёданд. Интизор шуда, такрор кунед.', loginError:'Воридшавӣ имкон нашуд. Email, рамз ва тасдиқи суроғаро санҷед.', requestError:'Дархост фиристода нашуд. Маълумотро санҷида, дертар такрор кунед.',
  },
  uk:{
    account:'Ваш акаунт', guestMode:'Гостьовий режим', guestDescription:'Зараз прогрес зберігається в цьому браузері. Увійдіть, щоб продовжити навчання на телефоні та зберегти свій профіль.', guestLogin:'Увійти · Google або email',
    profile:'Особистий профіль', name:'Ваше ім’я', saveName:'Зберегти ім’я', wait:'Зачекайте…', addPhoto:'Додати фото', removePhoto:'Видалити фото', photoHint:'JPEG, PNG або WebP до 5 МБ. Фото обрізається до квадрата та зберігається приватно.',
    profileSaved:'Профіль збережено.', profileError:'Не вдалося зберегти профіль.', profileRetry:'Не вдалося зберегти профіль. Спробуйте ще раз.', nameError:'Не вдалося зберегти ім’я.', nameInvalid:'Ім’я має містити від 2 до 60 символів.', photoInvalid:'Недопустиме фото.', loginUnavailable:'Вхід не підключено.', photoUploaded:'Фото оновлено.', photoUploadError:'Не вдалося завантажити фото.', photoUploadRetry:'Не вдалося завантажити фото. Спробуйте ще раз.', photoRemoved:'Фото видалено.', photoRemoveError:'Не вдалося видалити фото.', photoFormat:'JPEG, PNG або WebP, до 5 МБ.', photoSize:'Зображення завелике.', photoProcess:'Не вдалося обробити фото.',
    devices:'Збереження та пристрої', deviceDescription:'Ваші відповіді, XP, нотатки, налаштування та код доступні лише вашому акаунту. На іншому пристрої увійдіть у той самий акаунт.', sync:'Синхронізувати', importGuest:'Додати прогрес гостя з цього браузера', noGuestProgress:'Гостьового прогресу поки немає.', guestImported:'Гостьовий прогрес додано. Стан хмари показано нижче.', guestImportError:'Не вдалося прочитати гостьовий прогрес. Початкові дані збережено.',
    local:'У цьому браузері', syncing:'Зберігаємо у хмару…', synced:'Збережено у хмарі', offline:'Немає мережі · зміни збережено у браузері', error:'Хмара недоступна · зміни збережено у браузері',
    phone:'Продовжити на телефоні', phoneDescription:'Скануйте QR камерою, відкрийте сайт та увійдіть у той самий акаунт Google або email. QR містить лише посилання на сайт.', phoneAlt:'QR: відкрити вхід на телефоні', phoneError:'QR недоступний. Відкрийте цей сайт на телефоні.',
    security:'Захист акаунта', checking:'Перевіряємо…', connected:'Authenticator підключено', ordinaryLogin:'Звичайний вхід', securityDescription:'Додатковий захист через застосунок на телефоні. Працює без SMS: Google Authenticator, Microsoft Authenticator, 2FAS та інші.', enrollScan:'1. Скануйте QR у застосунку authenticator.', enrollCode:'2. Введіть код, щоб увімкнути захист.', enrollAlt:'QR для застосунку authenticator', enrollManual:'Не вдається сканувати? Введіть ключ вручну', enrollHint:'Збережіть доступ до застосунку: коди знадобляться під час наступного входу. Цей QR і ключ нікому не надсилайте.', appCode:'Код із застосунку', enableSecurity:'Підключити захист', cancel:'Скасувати', requiredCode:'Під час входу потрібен код із застосунку.', disable:'Відключити', enroll:'Підключити authenticator · QR', factorCheckError:'Не вдалося перевірити authenticator.', enrollError:'Не вдалося підключити authenticator. Спробуйте пізніше.', verifyError:'Код не прийнято. Візьміть новий код із застосунку.', cancelError:'Не вдалося скасувати підключення. Спробуйте ще раз.', factorRemoved:'Authenticator відключено.', factorRemoveError:'Не вдалося відключити authenticator. Підтвердьте вхід та повторіть.',
    session:'Сесія', sessionDescription:'Вхід зберігається на цьому пристрої після закриття браузера. Вихід закриє акаунт тут; на інших пристроях він залишиться відкритим.', logout:'Вийти', logoutAccount:'Вийти з акаунта',
    challengeTitle:'Підтвердьте вхід', challengeDescription:'Введіть 6 цифр із Google Authenticator, Microsoft Authenticator або іншого застосунку.', challengeCode:'Код authenticator', confirm:'Підтвердити', challengeError:'Не вдалося підтвердити код. Візьміть новий код із застосунку.',
    newPassword:'Новий пароль', recoveryDescription:'Після збереження увійдіть із новим паролем.', repeatPassword:'Повторіть пароль', savePassword:'Зберегти пароль', passwordMismatch:'Паролі не збігаються.', recoveryError:'Не вдалося змінити пароль. Повторіть запит відновлення.',
    opening:'Відкриваємо ReactMentor…', restoring:'Відновлюємо ваш вхід', openFailed:'Не вдалося відкрити акаунт', openError:'Не вдалося відкрити акаунт.', retry:'Повторити', assuranceError:'Не вдалося перевірити захист акаунта.', profileLoadError:'Не вдалося завантажити профіль. Перевірте з’єднання та налаштування бази.', connectionError:'Не вдалося перевірити з’єднання. Збережений вхід відновиться, коли з’явиться інтернет.', restoreError:'Збережений вхід тимчасово недоступний. Підключіться до інтернету — акаунт відновиться автоматично.', sessionExpired:'Сесія завершилася. Увійдіть ще раз.', sessionChanged:'Сесія змінилася. Повторіть відкриття акаунта.', accountUnverified:'Не вдалося підтвердити акаунт. Увійдіть ще раз.', loginIncomplete:'Вхід не завершено. Повторіть вхід через Google або email.', logoutError:'Не вдалося вийти. Спробуйте ще раз.',
    emailUnconfirmed:'Підтвердьте email за посиланням у листі, а потім увійдіть.', invalidCredentials:'Не вдалося увійти. Перевірте email і пароль.', signupDisabled:'Реєстрацію зараз закрито. Спробуйте пізніше або увійдіть у наявний акаунт.', weakPassword:'Пароль надто простий. Використайте щонайменше 8 символів, літери та цифри.', emailInvalid:'Перевірте адресу email: поштовий сервіс її не прийняв.', emailLimit:'Ліміт надсилання листів тимчасово вичерпано. Спробуйте пізніше.', requestLimit:'Забагато спроб. Зачекайте й повторіть.', loginError:'Не вдалося увійти. Перевірте email, пароль і підтвердження адреси.', requestError:'Не вдалося надіслати запит. Перевірте дані й повторіть пізніше.',
  },
};

const authErrorKeys: Record<string, AccountCopyKey> = {
  email_not_confirmed:'emailUnconfirmed', invalid_credentials:'invalidCredentials', signup_disabled:'signupDisabled', weak_password:'weakPassword', email_address_invalid:'emailInvalid', over_email_send_rate_limit:'emailLimit', over_request_rate_limit:'requestLimit',
};

/** Translate known provider codes without exposing raw backend error details. */
export function localizedAuthError(error: unknown, mode: 'login'|'signup'|'reset', language: InterfaceLocale) {
  const details = error && typeof error === 'object' ? error as {code?:unknown;status?:unknown} : {};
  const key = typeof details.code === 'string' && Object.hasOwn(authErrorKeys, details.code) ? authErrorKeys[details.code] : details.status === 429 ? 'requestLimit' : mode === 'login' ? 'loginError' : 'requestError';
  return ACCOUNT_COPY[language][key];
}

const localErrorKeys: AccountCopyKey[] = ['profileError','profileRetry','nameInvalid','photoInvalid','loginUnavailable','photoUploadError','photoUploadRetry','photoRemoveError','photoFormat','photoSize','photoProcess','openError','assuranceError','profileLoadError','connectionError','restoreError','sessionExpired','sessionChanged','accountUnverified','loginIncomplete','logoutError'];
const localErrors = new Map(localErrorKeys.map(key => [ru[key], key]));

/** The provider still owns auth behavior; the UI translates its known local errors. */
export function accountErrorKey(error: unknown, fallback: AccountCopyKey): AccountCopyKey {
  const message = typeof error === 'string' ? error : error instanceof Error ? error.message : '';
  return localErrors.get(message) || fallback;
}
