import type { InterfaceLocale } from './locale';

// Interface text is independent of the language selected for authored lessons
// and Tutor replies. This dictionary does not imply course translation coverage.
const ru = {
  testsInterview: 'Тесты и интервью', answersInterview: 'Ответы и интервью',
  assessmentIntro: 'Сначала проверьте знания, затем объясните решение своими словами.',
  tests: 'Тесты', interview: 'Интервью',
  allCourses: 'Все курсы', oneMonth: '1 месяц',
  planIntro: 'Выберите день. Изучите тему, выполните практику и проверьте себя.',
  dayIntro: 'Один день — один понятный шаг. Продолжаем предыдущую работу.',
  jsMonths: 'Месяцы JavaScript', month: 'Месяц', jsBasics: 'Основы и браузер', jsApps: 'API и приложения',
  courseUnavailable: 'Не удалось загрузить курс.', retry: 'Повторить',
  firstFile: 'От первого файла до проекта', completedDays: 'дней завершено · теория + практика каждый день',
  day: 'День', startZero: 'Начать с нуля', current: 'Сейчас', basics: 'База', harder: 'Сложнее', openDay: 'Открыть мой день',
  answersFlow: 'Вопрос → понятный ответ → пример',
  answersIntro: 'Единая библиотека подготовки к интервью. Откройте вопрос, разберите ответ и проверьте себя на практике.',
  checkYourself: 'Проверить себя', showMore: 'Показать ещё', chooseDay: 'Выбор дня', preparation: 'Подготовка',
  studyPlan: 'Учебный план', goDayOne: 'Перейти к дню 1',
  connections: 'Как связано с прошлыми днями',
  connectionsIntro: 'Добавьте новый шаг к результату этих уроков. Старые функции должны продолжать работать.',
  dayPractice: 'Практика этого дня', backExplanation: 'Вернуться к объяснению',
  testIntro: 'Выберите ответ и посмотрите объяснение.', interviewIntro: 'Объясните своими словами, затем сравните с ответом.',
  nextDay: 'Следующий день:', missingDay: 'Этот день отсутствует в плане. Выберите доступный день.',
  yourCode: 'Ваш код', showHtml: 'Показать HTML + CSS', htmlResult: 'Результат вашего HTML + CSS',
  preparationFallback: 'Материал подготовки пока доступен только на русском языке.',
  contentFallback: 'Некоторые материалы не переведены на выбранный язык обучения и показаны на русском.',
  tutorWelcome: 'Здравствуйте! Сначала найдём ответ в материалах проекта: бесплатно, без токенов. Для новых вопросов используется AI — войдите через Google или email.',
  tutorIntro: 'Сначала материалы проекта · AI для новых вопросов', tutorClose: 'Закрыть Tutor',
  tutorMaterial: 'Материалы проекта', tutorLocal: 'Локально', tokens: 'токенов', source: 'Источник:',
  tutorLoading: 'Ментор готовит ответ…',
  tutorSignIn: 'Материалы уроков — бесплатно. Для использования AI сначала войдите через Google или email.',
  tutorLogin: 'Вход / регистрация', tutorTopic: 'Тема курса', tutorDeep: 'Объясни подробнее',
  tutorQuestion: 'Вопрос к Tutor', tutorPlaceholder: 'Напишите вопрос или код…', tutorSend: 'Отправить',
  tutorSpent: 'В этом разговоре использовано:', tutorCaution: 'AI может ошибаться; проверяйте код.',
  tutorUnavailable: 'AI сейчас недоступен. Попробуйте позже.', tutorEmpty: 'Ответ пуст. Попробуйте позже.',
  tutorConnection: 'Соединение прервалось или AI не ответил вовремя. Попробуйте позже.',
  tutorInvalid: 'Вопрос или история чата некорректны либо слишком длинные.',
  tutorSignInRequired: 'Для вопроса к AI войдите через Google или email.',
  tutorAuthUnavailable: 'Вход в аккаунт пока не подключён. AI станет доступен после его настройки.',
  tutorUnconfigured: 'Ключ AI не настроен на сервере. Используйте материалы уроков.',
  tutorBusy: 'Подождите: запрос к AI уже отправлен.',
  tutorRejected: 'Ключ AI или доступ к модели не принят. Проверьте настройки сервера.',
  tutorQuota: 'Лимит или токены AnyModel закончились. Проверьте аккаунт провайдера.',
  tutorUnreadable: 'AI не прислал читаемый ответ. Попробуйте позже.',
  promptReact: 'Для чего нужен useState?', promptTopic: 'Подробно объясни первую тему курса.',
  promptDeep: 'Объясни предыдущий вопрос глубже, шаг за шагом.',
};

export const LEARNING_UI_COPY: Record<InterfaceLocale, typeof ru> = {
  ru,
  en: {
    testsInterview: 'Tests & interview', answersInterview: 'Answers & interview',
    assessmentIntro: 'Check your knowledge first, then explain the solution in your own words.',
    tests: 'Tests', interview: 'Interview', allCourses: 'All courses', oneMonth: '1 month',
    planIntro: 'Choose a day, study its topic, practice and check your understanding.',
    dayIntro: 'One day, one clear step. Build on your previous work.',
    jsMonths: 'JavaScript months', month: 'Month', jsBasics: 'Fundamentals and browser', jsApps: 'APIs and applications',
    courseUnavailable: 'Could not load the course.', retry: 'Retry',
    firstFile: 'From your first file to a project', completedDays: 'days completed · theory + practice every day',
    day: 'Day', startZero: 'Start from zero', current: 'Now', basics: 'Basics', harder: 'More advanced', openDay: 'Open my day',
    answersFlow: 'Question → clear answer → example',
    answersIntro: 'An interview preparation library. Open a question, study the answer and test yourself through practice.',
    checkYourself: 'Test yourself', showMore: 'Show more', chooseDay: 'Choose a day', preparation: 'Preparation',
    studyPlan: 'Study plan', goDayOne: 'Go to day 1', connections: 'Connections to previous days',
    connectionsIntro: 'Add the new step to the result of these lessons. Existing features should keep working.',
    dayPractice: 'Practice for this day', backExplanation: 'Back to the explanation',
    testIntro: 'Choose an answer and read the explanation.', interviewIntro: 'Explain in your own words, then compare with the answer.',
    nextDay: 'Next day:', missingDay: 'This day is not in the plan. Choose an available day.',
    yourCode: 'Your code', showHtml: 'Preview HTML + CSS', htmlResult: 'Your HTML + CSS result',
    preparationFallback: 'The preparation material is currently available only in Russian.',
    contentFallback: 'Some material is not translated into your selected learning language and is shown in Russian.',
    tutorWelcome: 'Hello! We first look for an answer in the project material: free, without tokens. AI handles new questions — sign in with Google or email.',
    tutorIntro: 'Project material first · AI for new questions', tutorClose: 'Close Tutor',
    tutorMaterial: 'Project material', tutorLocal: 'Local', tokens: 'tokens', source: 'Source:',
    tutorLoading: 'The mentor is preparing an answer…',
    tutorSignIn: 'Lesson material is free. To use AI, sign in with Google or email first.',
    tutorLogin: 'Sign in / register', tutorTopic: 'Course topic', tutorDeep: 'Explain more',
    tutorQuestion: 'Question for Tutor', tutorPlaceholder: 'Write your question or code…', tutorSend: 'Send',
    tutorSpent: 'Used in this conversation:', tutorCaution: 'AI can make mistakes; check the code.',
    tutorUnavailable: 'AI is currently unavailable. Try again later.', tutorEmpty: 'The answer is empty. Try again later.',
    tutorConnection: 'The connection was interrupted or AI took too long to respond. Try again later.',
    tutorInvalid: 'The question or chat history is invalid or too long.',
    tutorSignInRequired: 'Sign in with Google or email to ask AI a question.',
    tutorAuthUnavailable: 'Account sign-in is not connected yet. AI will be available after it is configured.',
    tutorUnconfigured: 'The AI key is not configured on the server. Use the lesson material.',
    tutorBusy: 'Please wait: an AI request has already been sent.',
    tutorRejected: 'The AI key or model access was rejected. Check the server settings.',
    tutorQuota: 'The AnyModel limit or tokens have run out. Check the provider account.',
    tutorUnreadable: 'AI did not return a readable answer. Try again later.',
    promptReact: 'What is useState for?', promptTopic: 'Explain the first course topic in depth.',
    promptDeep: 'Explain the previous question in more depth, step by step.',
  },
  tg: {
    testsInterview: 'Санҷишҳо ва мусоҳиба', answersInterview: 'Ҷавобҳо ва мусоҳиба',
    assessmentIntro: 'Аввал донишатонро санҷед, сипас ҳалли масъаларо бо суханони худ фаҳмонед.',
    tests: 'Санҷишҳо', interview: 'Мусоҳиба', allCourses: 'Ҳамаи курсҳо', oneMonth: '1 моҳ',
    planIntro: 'Рӯзро интихоб кунед. Мавзӯъро омӯзед, машқ кунед ва худро санҷед.',
    dayIntro: 'Як рӯз — як қадами равшан. Кори пешинаро идома медиҳем.',
    jsMonths: 'Моҳҳои JavaScript', month: 'Моҳ', jsBasics: 'Асосҳо ва браузер', jsApps: 'API ва барномаҳо',
    courseUnavailable: 'Курс бор карда нашуд.', retry: 'Аз нав кӯшиш кунед',
    firstFile: 'Аз файли аввал то лоиҳа', completedDays: 'рӯз анҷом ёфт · назария + машқ ҳар рӯз',
    day: 'Рӯз', startZero: 'Аз сифр оғоз кунед', current: 'Ҳоло', basics: 'Асосҳо', harder: 'Душвортар', openDay: 'Рӯзи маро кушоед',
    answersFlow: 'Савол → ҷавоби равшан → мисол',
    answersIntro: 'Китобхонаи омодагӣ ба мусоҳиба. Саволро кушоед, ҷавобро омӯзед ва худро дар амал санҷед.',
    checkYourself: 'Худро санҷед', showMore: 'Бештар нишон диҳед', chooseDay: 'Интихоби рӯз', preparation: 'Омодагӣ',
    studyPlan: 'Нақшаи омӯзиш', goDayOne: 'Ба рӯзи 1 гузаред', connections: 'Робита бо рӯзҳои гузашта',
    connectionsIntro: 'Қадами навро ба натиҷаи ин дарсҳо илова кунед. Имкониятҳои пешина бояд кор кунанд.',
    dayPractice: 'Машқи ин рӯз', backExplanation: 'Ба шарҳ баргардед',
    testIntro: 'Ҷавобро интихоб кунед ва шарҳро хонед.', interviewIntro: 'Бо суханони худ фаҳмонед, сипас бо ҷавоб муқоиса кунед.',
    nextDay: 'Рӯзи оянда:', missingDay: 'Ин рӯз дар нақша нест. Рӯзи дастрасро интихоб кунед.',
    yourCode: 'Коди шумо', showHtml: 'Нишон додани HTML + CSS', htmlResult: 'Натиҷаи HTML + CSS-и шумо',
    preparationFallback: 'Маводи омодагӣ ҳоло танҳо ба забони русӣ дастрас аст.',
    contentFallback: 'Баъзе мавод ба забони интихобшудаи омӯзиш тарҷума нашудааст ва ба русӣ нишон дода мешавад.',
    tutorWelcome: 'Салом! Аввал ҷавобро аз саволу ҷавобҳои лоиҳа меёбем: ройгон, бе токен. Барои саволи дар лоиҳа набуда AI истифода мешавад — бо аккаунти Google ё email ворид шавед.',
    tutorIntro: 'Аввал маводи лоиҳа · AI барои саволҳои нав', tutorClose: 'Пӯшидани Tutor',
    tutorMaterial: 'Маводи лоиҳа', tutorLocal: 'Локалӣ', tokens: 'токен', source: 'Манбаъ:',
    tutorLoading: 'Ментор ҷавоб тайёр мекунад…',
    tutorSignIn: 'Маводи дарсҳо — ройгон. Барои истифодаи AI аввал бо Google ё email ворид шавед.',
    tutorLogin: 'Воридшавӣ / регистрация', tutorTopic: 'Мавзӯи курс', tutorDeep: 'Чуқур фаҳмон',
    tutorQuestion: 'Савол ба Tutor', tutorPlaceholder: 'Савол ё кодатро навис…', tutorSend: 'Фиристодан',
    tutorSpent: 'Дар ин суҳбат сарф шуд:', tutorCaution: 'AI метавонад хато кунад; кодро санҷед.',
    tutorUnavailable: 'AI дастнорас аст.', tutorEmpty: 'Ҷавоб холӣ аст. Баъдтар кӯшиш кунед.',
    tutorConnection: 'Пайвастшавӣ қатъ шуд ё AI дер ҷавоб дод. Баъдтар кӯшиш кунед.',
    tutorInvalid: 'Савол ё таърихи чат нодуруст ё хеле дароз аст.',
    tutorSignInRequired: 'Барои саволи AI бо Google ё email ба аккаунт ворид шавед.',
    tutorAuthUnavailable: 'Воридшавӣ ба аккаунт ҳоло пайваст нашудааст. AI баъди пайваст шудани воридшавӣ дастрас мешавад.',
    tutorUnconfigured: 'Калиди AI дар сервер танзим нашудааст. Аз дарсҳои платформа истифода баред.',
    tutorBusy: 'Каме интизор шавед: дархости AI аллакай фиристода шудааст.',
    tutorRejected: 'Калиди AI ё дастрасӣ ба модел қабул нашуд. Танзимоти серверро санҷед.',
    tutorQuota: 'Лимит ё токенҳои AnyModel тамом шуданд. Ҳисоби провайдерро санҷед.',
    tutorUnreadable: 'AI ҷавоби хондашаванда нафиристод. Баъдтар кӯшиш кунед.',
    promptReact: 'useState чиба даркорай?', promptTopic: 'Мавзӯи аввалро чуқур фаҳмон.',
    promptDeep: 'Саволи пешинаро қадам ба қадам чуқуртар фаҳмон.',
  },
  uk: {
    testsInterview: 'Тести та співбесіда', answersInterview: 'Відповіді та співбесіда',
    assessmentIntro: 'Спочатку перевірте знання, потім поясніть рішення своїми словами.',
    tests: 'Тести', interview: 'Співбесіда', allCourses: 'Усі курси', oneMonth: '1 місяць',
    planIntro: 'Оберіть день. Вивчіть тему, виконайте практику та перевірте себе.',
    dayIntro: 'Один день — один зрозумілий крок. Продовжуємо попередню роботу.',
    jsMonths: 'Місяці JavaScript', month: 'Місяць', jsBasics: 'Основи та браузер', jsApps: 'API та застосунки',
    courseUnavailable: 'Не вдалося завантажити курс.', retry: 'Спробувати знову',
    firstFile: 'Від першого файлу до проєкту', completedDays: 'днів завершено · теорія + практика щодня',
    day: 'День', startZero: 'Почати з нуля', current: 'Зараз', basics: 'Основи', harder: 'Складніше', openDay: 'Відкрити мій день',
    answersFlow: 'Питання → зрозуміла відповідь → приклад',
    answersIntro: 'Бібліотека підготовки до співбесіди. Відкрийте питання, розберіть відповідь і перевірте себе на практиці.',
    checkYourself: 'Перевірити себе', showMore: 'Показати ще', chooseDay: 'Вибір дня', preparation: 'Підготовка',
    studyPlan: 'Навчальний план', goDayOne: 'Перейти до дня 1', connections: 'Зв’язок із попередніми днями',
    connectionsIntro: 'Додайте новий крок до результату цих уроків. Попередні можливості мають працювати.',
    dayPractice: 'Практика цього дня', backExplanation: 'Повернутися до пояснення',
    testIntro: 'Оберіть відповідь і прочитайте пояснення.', interviewIntro: 'Поясніть своїми словами, потім порівняйте з відповіддю.',
    nextDay: 'Наступний день:', missingDay: 'Цього дня немає у плані. Оберіть доступний день.',
    yourCode: 'Ваш код', showHtml: 'Показати HTML + CSS', htmlResult: 'Результат вашого HTML + CSS',
    preparationFallback: 'Матеріал підготовки поки доступний лише російською мовою.',
    contentFallback: 'Деякі матеріали не перекладені обраною мовою навчання та показані російською.',
    tutorWelcome: 'Вітаємо! Спочатку знайдемо відповідь у матеріалах проєкту: безкоштовно, без токенів. Для нових питань використовується AI — увійдіть через Google або email.',
    tutorIntro: 'Спочатку матеріали проєкту · AI для нових питань', tutorClose: 'Закрити Tutor',
    tutorMaterial: 'Матеріали проєкту', tutorLocal: 'Локально', tokens: 'токенів', source: 'Джерело:',
    tutorLoading: 'Ментор готує відповідь…',
    tutorSignIn: 'Матеріали уроків — безкоштовно. Для використання AI спочатку увійдіть через Google або email.',
    tutorLogin: 'Вхід / реєстрація', tutorTopic: 'Тема курсу', tutorDeep: 'Поясни докладніше',
    tutorQuestion: 'Питання до Tutor', tutorPlaceholder: 'Напишіть питання або код…', tutorSend: 'Надіслати',
    tutorSpent: 'У цій розмові використано:', tutorCaution: 'AI може помилятися; перевіряйте код.',
    tutorUnavailable: 'AI зараз недоступний. Спробуйте пізніше.', tutorEmpty: 'Відповідь порожня. Спробуйте пізніше.',
    tutorConnection: 'З’єднання перервано або AI не відповів вчасно. Спробуйте пізніше.',
    tutorInvalid: 'Питання або історія чату некоректні чи надто довгі.',
    tutorSignInRequired: 'Для питання до AI увійдіть через Google або email.',
    tutorAuthUnavailable: 'Вхід до акаунта поки не підключено. AI стане доступним після налаштування.',
    tutorUnconfigured: 'Ключ AI не налаштований на сервері. Використовуйте матеріали уроків.',
    tutorBusy: 'Зачекайте: запит до AI вже надіслано.',
    tutorRejected: 'Ключ AI або доступ до моделі відхилено. Перевірте налаштування сервера.',
    tutorQuota: 'Ліміт або токени AnyModel закінчилися. Перевірте акаунт провайдера.',
    tutorUnreadable: 'AI не надіслав читабельної відповіді. Спробуйте пізніше.',
    promptReact: 'Для чого потрібен useState?', promptTopic: 'Докладно поясни першу тему курсу.',
    promptDeep: 'Поясни попереднє питання глибше, крок за кроком.',
  },
};

export type TutorErrorKey = 'tutorUnavailable' | 'tutorEmpty' | 'tutorConnection' | 'tutorInvalid'
  | 'tutorSignInRequired' | 'tutorAuthUnavailable' | 'tutorUnconfigured' | 'tutorBusy'
  | 'tutorRejected' | 'tutorQuota' | 'tutorUnreadable';

// The current API supplies messages rather than stable codes. Recognize known
// application failures; never show untrusted provider or browser errors as UI.
export function tutorErrorKey(status: number, message: unknown): TutorErrorKey {
  if (typeof message === 'string') {
    for (const key of ['tutorSignInRequired', 'tutorAuthUnavailable', 'tutorUnconfigured', 'tutorBusy', 'tutorRejected', 'tutorQuota', 'tutorUnreadable', 'tutorInvalid'] as const) {
      if (message === LEARNING_UI_COPY.tg[key]) return key;
    }
  }
  if (status === 401) return 'tutorSignInRequired';
  if (status === 400) return 'tutorInvalid';
  if (status === 429) return 'tutorQuota';
  return 'tutorUnavailable';
}
