import { expect, test } from '@playwright/test';
import quiz from '../src/content/imported/quiz.json';

test('answers library filters, searches, exports and preserves reading progress and notes', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/answers');
  await expect(page.getByRole('heading', { name: 'Ответы', exact: true })).toBeVisible();
  await expect(page.locator('.answer-topic-card')).toHaveCount(18);
  await expect(page.locator('.answers-intro')).toContainText('473');
  await page.locator('.answers-source-filters').getByRole('link', { name: 'Тесты', exact: true }).click();
  await expect(page.locator('.answers-source-filters').getByRole('link', { name: 'Тесты', exact: true })).toHaveAttribute('aria-current', 'page');
  await page.locator('.answer-group').filter({ hasText: 'Группа 2' }).click();
  await expect(page.locator('.answers-pagination')).toContainText('1 / 2');
  await expect(page.locator('.answer-topic-card').first()).toContainText('Группа 2');
  await page.locator('.answers-source-filters').getByRole('link', { name: 'Все', exact: true }).click();
  await expect(page.locator('.answers-source-filters').getByRole('link', { name: 'Все', exact: true })).toHaveAttribute('aria-current', 'page');
  await expect(page).toHaveURL('/answers');
  await page.getByRole('searchbox').fill('/products/:id');
  await page.getByRole('button', { name: 'Найти', exact: true }).click();
  await expect(page.locator('.answer-topic-card[href="/answers/deep-71"]')).toBeVisible();
  await expect(page.getByRole('searchbox')).toHaveValue('/products/:id');
  await page.locator('.answer-topic-card[href="/answers/deep-71"]').click();
  await expect(page.locator('.lesson-article pre')).toContainText('// Route: /products/:id');
  await expect(page.locator('.flow-steps')).toContainText('UI update');
  await page.goto('/answers/deep-1');
  await expect(page.locator('.answer-reading-body').first()).toContainText(quiz.groups[0].items[0].correctAnswer);
  await page.getByRole('button', { name: 'Прочитал и понял', exact: true }).first().click();
  await page.getByRole('button', { name: 'В заметки', exact: true }).first().click();
  await page.reload();
  await expect(page.getByRole('button', { name: 'Изучено', exact: true }).first()).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Сохранено', exact: true }).first()).toBeDisabled();
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('react-mentor-learning-v2')!).state);
  expect(stored.studied).toContain('quiz-q001');
  expect(stored.awards['learn:quiz-q001']).toBe(2);
  expect(stored.notes.filter((note: {id:string}) => note.id === 'answer:quiz-q001')).toHaveLength(1);
  await page.goto('/notes');
  await expect(page.locator('main')).toContainText(quiz.groups[0].items[0].question);
  await page.goto('/answers?source=interview');
  await expect(page.locator('.answer-topic-card').first()).toContainText('Interview');
  await page.locator('.answer-topic-card').first().click();
  await expect(page.locator('.answer-reading-body pre').first()).toBeVisible();
  await page.goto('/answers/interview-3');
  await expect(page.locator('#interview-q7 .flow-steps')).toContainText('Paint: намоиш');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: '/tmp/react-mentor-' + testInfo.project.name + '-answer-reader.png', fullPage: true });
  await page.goto('/answers');
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Скачать общий HTML' }).click();
  const download = await downloadEvent;
  expect(download.suggestedFilename()).toBe('react-answers.html');
  const response = await page.request.get('/answers/export');
  expect(response.headers()['content-security-policy']).toContain('sandbox');
  expect((await response.text()).match(/class="question"/g)).toHaveLength(473);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: '/tmp/react-mentor-' + testInfo.project.name + '-answers.png', fullPage: true });
  expect(errors).toEqual([]);
});
